apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:6.4.3
        imagePullPolicy: Always
        name: kibana
        ports:
        - containerPort: 5601
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/share/kibana/config/
          name: config-volume
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: kibana-config
          items:
          - key: kibana.yml
            path: kibana.yml
        name: config-volume
