apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
  - name: api
    port: 9600
    protocol: TCP
    targetPort: 9600
  - name: gelf
    port: 44622
    protocol: UDP
    targetPort: 44622
  selector:
    name: logstash
